GHCR image push-restic-backup-restore
silinternational/restic-backup-restore pull request #9
Opened 2024-10-04 11:15 UTC by Praveenraj-K

-Pushing the images in both Docker Hub & GitHub Container Registry "GHCR.io"
-Only initiate when there is a commit in the main branch using the workflow trigger.

2024-10-04 11:30 UTC, devon-sil commented
@Praveenraj-K Thanks for putting together a PR for this. I've added the developers for review.

2024-10-07 10:27 UTC, briskt requested changes
same comments as other repos

2024-10-07 10:27 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +      - main
This should include `tags` as well

2024-10-07 10:27 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +            type=ref,event=branch  # Tag with branch name
This should include `semver` or `type=ref,event=tag` as well.

2024-10-08 06:34 UTC, briskt approved these changes

2024-10-08 14:00 UTC, merged